### ISSUE TITLE
about the scorep-autofilter tool

### ISSUE THREAD

**Issue by Synlvejo** [readex-eu/readex-scorep#1]
hello, i have read the paper "Modelling DVFS and UFS for Region-Based Energy Aware Tuning of HPC Applications" and want to achieve it to make a report, but i found the "scorep-autofilter tool" is not involved in any score-p source or the "The READEX formalism for automatic tuning for energy efficiency". So i wanna know how can i get this tool ? Thanks for any answer.

**Comment by rschoene** [comment]
Hi,
It's part of readex-ptf's cube_tools. I assigned your issue to the responsible developers in case you have further questions.

**Comment by madhurakswamy** [comment]
Hello,
The scorep-autofilter tool is part of the Periscope Tuning Framework. Please clone the readex-ptf repository. The source code for scorep-autofilter is under readex-ptf/readex/cube_tools/filter_regions.

**Comment by Synlvejo** [comment]
> Hi,
> It's part of readex-ptf's cube_tools. I assigned your issue to the responsible developers in case you have further questions.

Oh it's soooo great , i have been finding the autofilter tool and readex-dyn-detect tool for a long time,TAT. And i guess the tuning_potential must be the readex-dyn-detect tool,lol, thanks a lot !

**Comment by Synlvejo** [comment]
> Hello,
> The scorep-autofilter tool is part of the Periscope Tuning Framework. Please clone the readex-ptf repository. The source code for scorep-autofilter is under readex-ptf/readex/cube_tools/filter_regions.

The same thanks as rschoene for you,too. So many words "copy from the last reply", thanks~

**Comment by madhurakswamy** [comment]
> Oh it's soooo great , i have been finding the autofilter tool and readex-dyn-detect tool for a long time,TAT. And i guess the tuning_potential must be the readex-dyn-detect tool,lol, thanks a lot !

Yes, that's right.

**Comment by Synlvejo** [comment]
> Hi,
> It's part of readex-ptf's cube_tools. I assigned your issue to the responsible developers in case you have further questions.
